class server::webserver::apache2(
  $default_mods,
  $default_vhost,
  $default_ssl_vhost,
  $default_ssl_cert,
  $default_ssl_key,
  $default_ssl_chain,
  $default_ssl_ca,
  $default_ssl_crl_path,
  $default_ssl_crl,
  $service_enable,
  $service_ensure,
  $purge_configs,
  $purge_vdir,
  $serveradmin,
  $sendfile,
  $error_documents,
  $timeout,
  $httpd_dir,
  $confd_dir,
  $vhost_dir,
  $vhost_enable_dir,
  $mod_dir,
  $mod_enable_dir,
  $mpm_module,
  $conf_template,
  $servername,
  $manage_user,
  $manage_group,
  $user,
  $group,
  $keepalive,
  $keepalive_timeout,
  $logroot,
  $ports_file,
  $server_tokens,
  $server_signature,
  $package_ensure,
) {
  class { 'apache': 
    default_mods         => $default_mods,
    default_vhost        => $default_vhost,
    default_ssl_vhost    => $default_ssl_vhost,
    default_ssl_cert     => $default_ssl_cert,
    default_ssl_key      => $default_ssl_key,
    default_ssl_chain    => $default_ssl_chain,
    default_ssl_ca       => $default_ssl_ca,
    default_ssl_crl_path => $default_ssl_crl_path,
    default_ssl_crl      => $default_ssl_crl,
    service_enable       => $service_enable,
    service_ensure       => $service_ensure,
    purge_configs        => $purge_configs,
    purge_vdir           => $purge_vdir,
    serveradmin          => $serveradmin,
    sendfile             => $sendfile,
    error_documents      => $error_documents,
    timeout              => $timeout,
    httpd_dir            => $httpd_dir,
    confd_dir            => $confd_dir,
    vhost_dir            => $vhost_dir,
    vhost_enable_dir     => $vhost_enable_dir,
    mod_dir              => $mod_dir,
    mod_enable_dir       => $mod_enable_dir,
    mpm_module           => $mpm_module,
    conf_template        => $conf_template,
    servername           => $servername,
    manage_user          => $manage_user,
    manage_group         => $manage_group,
    user                 => $user,
    group                => $group,
    keepalive            => $keepalive,
    keepalive_timeout    => $keepalive_timeout,
    logroot              => $logroot,
    ports_file           => $ports_file,
    server_tokens        => $server_tokens,
    server_signature     => $server_signature,
    package_ensure       => $package_ensure,
  }

  # apache::mod { 'actions': }
  # apache::mod { 'rewrite': }
  # apache::mod { 'fastcgi': }
  # apache::mod { 'proxy': }
  # apache::mod { 'proxy_http': }
}
